//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_TechPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordenes
    {
        public int idOrden { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string direccion { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public string estado { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
