//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_TechPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.Ordenes = new HashSet<Ordenes>();
        }
    
        public int idProducto { get; set; }
        public string nombreProducto { get; set; }
        public Nullable<int> precio { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public string imagen { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Invetario Invetario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordenes> Ordenes { get; set; }
    }
}
