//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_TechPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int idProducto { get; set; }
        public string nombreProducto { get; set; }
        public Nullable<int> precio { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public string imagen { get; set; }
    
        public virtual Invetario Invetario { get; set; }
    }
}
