//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_TechPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int idUsuario { get; set; }
        public Nullable<int> telefono { get; set; }
        public string email { get; set; }
        public Nullable<int> idDireccion { get; set; }
        public string nombre { get; set; }
        public string primerApellido { get; set; }
        public string segundoApellido { get; set; }
    
        public virtual Direccion Direccion { get; set; }
    }
}
